### PR TITLE
Exclusive lists

### PR DESCRIPTION
**Pull request by necropolina**
Cherry picked from https://github.com/mastodon/mastodon/pull/22048

Looks like one of the things glitch did to prevent upstream changes from breaking glitch functionality is they added the `app/javascript/flavours/glitch` directory. So I just added the changes in there instead of both places. :P

### CODE REVIEW

**Comment by sneakers-the-rat** [comment]
let's pull to dev bc it's been updated from upstream, and figure out how to write tests, this seems like a good feature to learn on I think

**Comment by necropolina** [comment]
sounds good! merged dev into this branch, can prolly chat about tests in discord

**Comment by sneakers-the-rat** [comment]
k i wasn't sure what would happen if i pushed just then but i did and now things are happening.

**Comment by sneakers-the-rat** [comment]
I approve of these commits

**Pull request closed without merging**
